"project_identifier" : "beyond-the-camp"
"base_path" : "/src"
"preserve_hierarchy": true

files: [
 {
  "source" : "/i18n/en.json",
  "translation" : "/i18n/%two_letters_code%.json",
 },
 {
  "source" : "/pages/en/projects/*.md",
  "translation" : "/pages/%two_letters_code%/projects/%original_file_name%",
 },
 {
  "source" : "/pages/en/categories/*.md",
  "translation" : "/pages/%two_letters_code%/categories/%original_file_name%",
 }
]