"project_identifier" : "beyond-the-camp"
"base_path" : "/cms"
"preserve_hierarchy": true

files: [
 {
  "source" : "/en/projects/*.md",
  "translation" : "/%two_letters_code%/projects/%original_file_name%",
 },
 {
  "source" : "/en/categories/*.md",
  "translation" : "/%two_letters_code%/categories/%original_file_name%",
 }
]