backend:
  name: git-gateway
  branch: netlifycms # Branch to update (optional; defaults to master)
  # name: test-repo

# publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: 'content/projects/en'
    extension: md
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured image', name: 'featuredImage', widget: 'image' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          multiple: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: categories
    label: Categories
    folder: 'content/categories/en'
    extension: md
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
