backend:
  name: git-gateway
  # name: test-repo
  branch: netlifycms # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: 'content/projects'
    extension: md
    create: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          multiple: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: categories
    label: Categories
    folder: 'content/categories'
    extension: md
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
