backend:
  name: git-gateway
  # name: test-repo

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: 'src/pages/en/projects'
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Cover image', name: 'cover', widget: 'image' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          multiple: true,
        }
      - label: 'Opening times'
        name: 'openingTimes'
        widget: 'list'
        fields:
          - label: 'Day'
            name: day
            widget: 'select'
            options:
              [
                'Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday',
                'Sunday',
              ]
          - label: 'Open'
            name: 'open'
            widget: 'datetime'
            dateFormat: false
            default: 2018-01-01T09:00:00.000Z
          - label: 'Close'
            name: 'close'
            widget: 'datetime'
            dateFormat: false
            default: 2018-01-01T17:00:00.000Z

      - { label: 'Body', name: 'body', widget: 'markdown' }

      - label: 'Location'
        name: location
        widget: object
        fields:
          - label: 'Description'
            name: 'description'
            hint: 'Text description of the location'
            widget: 'string'
          - label: 'Show map'
            name: 'showMap'
            hint: 'Show a map of the location?'
            widget: 'boolean'
            default: false
          - label: 'Map'
            name: 'geo'
            widget: 'map'
            default: '{ "type": "Point", "coordinates": [26.5172195, 39.1297939] }'

  - name: categories
    label: Categories
    folder: 'src/pages/en/categories'
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
