backend:
  # name: test-repo
  name: git-gateway

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: projects
    label: Projects
    folder: 'src/pages/en/projects'
    extension: md
    create: true
    preview_path: 'en/projects/{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Cover image',
          name: 'cover',
          widget: 'image',
          required: false,
        }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          searchFields: ['title'],
          valueField: 'title',
          multiple: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

      - label: 'Opening times'
        name: 'openingTimes'
        widget: 'list'
        fields:
          - label: 'Day'
            name: day
            widget: 'select'
            options:
              [
                'Monday',
                'Tuesday',
                'Wednesday',
                'Thursday',
                'Friday',
                'Saturday',
                'Sunday',
              ]
          - label: 'Open'
            name: 'open'
            widget: 'datetime'
            dateFormat: false
            default: 2018-01-01T09:00:00.000Z
          - label: 'Close'
            name: 'close'
            widget: 'datetime'
            dateFormat: false
            default: 2018-01-01T17:00:00.000Z

      - label: 'Location'
        name: location
        widget: object
        fields:
          - label: 'Description'
            name: 'description'
            hint: 'Text description of the location'
            widget: 'string'

  - name: categories
    label: Categories
    folder: 'src/pages/en/categories'
    extension: md
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
