backend:
  name: git-gateway
  branch: netlifycms # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'projects' # Used in routes, e.g., /admin/collections/blog
    label: 'Projects' # Used in the UI
    folder: 'src/cms/projects' # The path to the folder where the documents are stored
    create: true
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - {
          label: 'Categories',
          name: 'categories',
          widget: 'relation',
          collection: 'categories',
          displayFields: ['category'],
          multiple: true,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'categories'
    label: 'Categories'
    folder: 'src/cms/categories'
    create: true
    fields:
      - { label: 'Category', name: 'category', widget: 'string' }
